name: 手机号登录
on:
  workflow_dispatch:
    inputs:
      step:
        description: "操作步骤"
        required: true
        type: choice
        default: "发送验证码"
        options:
          - 发送验证码
          - 登录
      append_user:
        description: "是否追加新账号？（不删除已存在账号信息）"
        required: true
        type: choice
        default: "否"
        options:
          - 是
          - 否
permissions:
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      - name: 创建 Node 环境
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: 检查 GitHub CLI
        if: github.event.inputs.step == '登录'
        run: |
          if ! command -v gh >/dev/null 2>&1; then
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
          fi
          gh --version
      - name: 缓存依赖
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ./api/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: 安装依赖
        run: npm run install
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      - name: 发送验证码
        if: github.event.inputs.step == '发送验证码'
        run: npm run sent
        env:
          PHONE: ${{ secrets.PHONE }}
      - name: 手机号登录
        if: github.event.inputs.step == '登录'
        run: npm run phoneLogin
        env:
          PHONE: ${{ secrets.PHONE }}
          CODE: ${{ secrets.CODE }}
          PAT: ${{ secrets.PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          USERINFO: ${{ secrets.USERINFO }}
          APPEND_USER: ${{ github.event.inputs.append_user }}
